[controls.axes.Rotation]
emulated = { pos = { key = "Right" }, neg = { key = "Left" } }

[controls.axes.Depth]
emulated = { pos = { key = "Up" }, neg = { key = "Down" } }

[controls.actions.AddEntity]
combinations = [[{ key = "Z" }]]
once = true

[controls.actions.DeleteEntity]
combinations = [[{ key = "X" }]]
once = true


# Usage

# Axis

# With keyboard keys
# [controls.axes.XXX]
# emulated = { pos = { key = "Right" }, neg = { key = "Left" } }

# With mouse buttons
# [controls.axes.XXX]
# emulated = { pos = { mouse_button = "MouseButtonRight" }, neg = { mouse_button = "MouseButtonLeft" } }

# With gamepad buttons
# [controls.axes.XXX.emulated]
# pos = { controller = { id = 0, button = "GamepadButton15" } }
# neg = { controller = { id = 0, button = "GamepadButton14" } }

# With gamepad axis
# [controls.axes.XXX]
# controller_axis = { id = 0, axis = 0, invert = false, dead_zone = 0.2 }

# With mouse axis
# [controls.axes.XXX]
# mouse_axis = { axis = 0 }


# Actions
# [controls.actions.XXX]
# combinations = [
#     [{ key = "Control" }, { key = "Q" }],
#     [{ key = "Escape" }]
# ]
# once = true
