[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 600, height = 600, color = [150, 150, 200, 255] }

    [entity.components.Transform]
    translation = { x = 300.0, y = 300.0 }
    depth = -1.0


[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "bat"
    sprite_number = 0

    [entity.components.Transform]
    translation = { x = 160.0, y = 440.0 }

    [entity.components.AnimationControl]
    sprite_sheet_name = "bat"
    animation_name = "fly1"
    end = { type = "Loop" }
    command = { type = "Start" }
    rate_multiplier = 1.0


[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "bat"
    sprite_number = 6

    [entity.components.Transform]
    translation = { x = 460.0, y = 440.0 }

    [entity.components.AnimationControl]
    sprite_sheet_name = "bat"
    animation_name = "fly2"
    end = { type = "Loop" }
    command = { type = "Start" }
    rate_multiplier = 1.0


[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "bat"
    sprite_number = 6

    [entity.components.Transform]
    translation = { x = 160.0, y = 140.0 }

    [entity.components.AnimationControl]
    sprite_sheet_name = "bat"
    animation_name = "fly2"
    end = { type = "Normal" }
    command = { type = "Start" }
    rate_multiplier = 1.0


[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "bat"
    sprite_number = 6

    [entity.components.Transform]
    translation = { x = 460.0, y = 140.0 }

    [entity.components.AnimationControl]
    sprite_sheet_name = "bat"
    animation_name = "fly2"
    end = { type = "Stay" }
    command = { type = "Start" }
    rate_multiplier = 1.0
